#
# Project: Simu5G-NR-EDF
# Authors: Alaf Nascimento, Philippe Martins, Samuel Tardieu, and Laurent Pautet
# Institution: Télécom Paris, Institut Polytechnique de Paris
# Contact: {firstname.lastname}@telecom-paris.fr
#
# Description: Python scripts to process and analyze data generated by Simu5G-NR-EDF simulations
#

import definitions as d
VERSIONS = ["v7", "v8"]

all_avgs = {}
for version in VERSIONS:
    data = d.collect_results(version)
    if data:
        averages = d.compute_averages(data)
        all_avgs[version] = averages
        d.print_table(averages, version)
    
if all_avgs:
    d.plot_results(all_avgs, LOG_X=False, LOG_Y=False)
