#
# Project: Simu5G-NR-EDF
# Authors: Alaf Nascimento, Philippe Martins, Samuel Tardieu, and Laurent Pautet
# Institution: Télécom Paris, Institut Polytechnique de Paris
# Contact: {firstname.lastname}@telecom-paris.fr
#
# Description: Python scripts to process and analyze data generated by Simu5G-NR-EDF simulations
#

import sys
import numpy as np
import json
import definitions as d

if len(sys.argv) < 2:
    print("Usage: python json_analysis.py <json_option>")
    sys.exit(1)

json_file = "data/"+str(sys.argv[1])+".json"
with open(json_file, "r") as f:
    data = json.load(f)
    
missed_deadline_values = []
nbPkt_values = []
missed_deadline_rate_values = []
mac_throughput_values =  []

for entry in data:
    missed_deadline_values.append(entry["MissedDeadlineCounter"])
    nbPkt_values.append(entry["PktCounter"])
    mac_throughput_values.append(entry["MacThroughput"])
    if entry["PktCounter"] > 0:
        missed_deadline_rate_values.append(100*(entry["MissedDeadlineCounter"]/entry["PktCounter"]))

if np.sum(nbPkt_values) == 0 and np.sum(mac_throughput_values) == 0:
    print("Number of Packets: ", 0)
else:
    # Compute averages
    print(f"Average Number of RT Packets: {np.mean(nbPkt_values)} packets (from {len(nbPkt_values)} runs)")
    if np.sum(nbPkt_values) > 0:
        print(f"Average Missed Deadline: {np.mean(missed_deadline_values)} packets (from {len(missed_deadline_values)} runs)")
    print(f"Average MAC Throughput: {np.mean(mac_throughput_values)} Bps (from {len(mac_throughput_values)} runs)\n")

    # Compute confidence interval
    missed_ci = d.compute_confidence_interval(missed_deadline_values)
    print(f"95% CI for Missed Deadlines Per Repetition: {missed_ci}")