#
# Project: Simu5G-NR-EDF
# Authors: Alaf Nascimento, Philippe Martins, Samuel Tardieu, and Laurent Pautet
# Institution: Télécom Paris, Institut Polytechnique de Paris
# Contact: {firstname.lastname}@telecom-paris.fr
#
# Description: Python scripts to process and analyze data generated by Simu5G-NR-EDF simulations
#

import json
import matplotlib.pyplot as plt
import numpy as np

def load_results(filepath):
    with open(filepath, "r") as f:
        data = json.load(f)
    app_totals = {}
    for entry in data:
        for app_dict in entry["Apps"]:
            for app, value in app_dict.items():
                app_totals[app] = app_totals.get(app, 0) + value
    return app_totals

edf_results = load_results("data/results_dcgbr_v7_edf3.json")
pf_results = load_results("data/results_dcgbr_v7_pf3.json")

apps = sorted(set(edf_results.keys()) | set(pf_results.keys()), key=int)
edf_values = [edf_results.get(app, 0) for app in apps]
pf_values = [pf_results.get(app, 0) for app in apps]

x = np.arange(len(apps))
width = 0.35

plt.figure(figsize=(8,5))
plt.bar(x - width/2, edf_values, width, label="EDF")
plt.bar(x + width/2, pf_values, width, label="PF")

plt.xlabel("App")
plt.ylabel("Missed Deadlines (sum)")
plt.title("Comparison of Missed Deadlines per App")
plt.xticks(x, apps)
plt.legend()
plt.tight_layout()
plt.show()
