#
# Project: Simu5G-NR-EDF
# Authors: Alaf Nascimento, Philippe Martins, Samuel Tardieu, and Laurent Pautet
# Institution: Télécom Paris, Institut Polytechnique de Paris
# Contact: {firstname.lastname}@telecom-paris.fr
#
# Description: Python scripts to process and analyze data generated by Simu5G-NR-EDF simulations
#

import sys
import glob
import numpy as np
import definitions as d

if len(sys.argv) < 2:
    print("Usage: python sca_analysis.py <folder_option>")
    sys.exit(1)

folder = "data/"+str(sys.argv[1])+"/SCADA/*.sca"
sca_files = glob.glob(folder)

missed_deadline_rate_values = []
nbPkt_values = []
missed_deadline_values = []
mac_throughput_values =  []
for f in sca_files:
    missed_deadline = 0
    nb_pkt = 0
    mac_throughput = 0
    with open(f) as file:
        for line in file:
            if line.startswith("scalar"):
                if "cbrMissedPktDeadline:mean" in line:
                    missed_deadline += d.get_value(line)
                elif "cbrPktCounter:mean" in line:
                    nb_pkt += d.get_value(line)
                elif "gnb" in line and "macCellThroughputDl:mean" in line:
                    mac_throughput += d.get_value(line)
    nbPkt_values.append(nb_pkt)
    missed_deadline_values.append(missed_deadline)
    mac_throughput_values.append(mac_throughput)
    if nb_pkt > 0:
        missed_deadline_rate_values.append(100*(missed_deadline/nb_pkt))

if np.sum(nbPkt_values) == 0 and np.sum(mac_throughput_values) == 0:
    print("Number of Packets: ", 0)
else:
    # Compute averages
    print(f"Average Number of RT Packets: {np.mean(nbPkt_values)} packets (from {len(nbPkt_values)} runs)")
    if np.sum(nbPkt_values) > 0:
        print(f"Average Missed Deadline: {np.mean(missed_deadline_values)} packets (from {len(missed_deadline_values)} runs)")
    print(f"Average MAC Throughput: {np.mean(mac_throughput_values)} Bps (from {len(mac_throughput_values)} runs)\n")

    # Compute confidence interval
    missed_ci = d.compute_confidence_interval(missed_deadline_values)
    print(f"95% CI for Missed Deadlines Per Repetition: {missed_ci}")
