#
# Project: Simu5G-NR-EDF
# Authors: Alaf Nascimento, Philippe Martins, Samuel Tardieu, and Laurent Pautet
# Institution: Télécom Paris, Institut Polytechnique de Paris
# Contact: {firstname.lastname}@telecom-paris.fr
#
# Description: Python scripts to process and analyze data generated by Simu5G-NR-EDF simulations
#

import sys
import glob
import definitions as d
import json
    
if len(sys.argv) < 2:
    print("Usage: python sca_to_json.py <folder_option>")
    sys.exit(1)

folder = "data/"+str(sys.argv[1])+"/SCADA/*.sca"
sca_files = glob.glob(folder)

output_json = []
for f in sca_files:
    missed_deadline = 0
    nb_pkt = 0
    apps = []
    scheduled = False
    mac_throughput = 0
    with open(f) as file:
        for line in file:
            if line.startswith("scalar"):
                if "cbrMissedPktDeadline:mean" in line:
                    value = d.get_value(line)
                    missed_deadline += value
                    apps.append({d.get_app(line):value})
                elif "gnb" in line and "macCellThroughputDl:mean" in line:
                    mac_throughput += d.get_value(line)
                elif "cbrPktCounter:mean" in line:
                    nb_pkt += d.get_value(line)
    scheduled = missed_deadline == 0
    output_json.append({"File": f, "MissedDeadlineCounter": missed_deadline, "PktCounter": nb_pkt, "Apps":apps, "Schedulable":scheduled, "MacThroughput": mac_throughput})

output_file = folder.split("/")[1].replace(".sca", "") + ".json"
with open("data/"+output_file, "w") as f:
    json.dump(output_json, f, indent=4)  # indent=4 makes it pretty